# fly.toml app configuration file generated for withered-glade-5107 on 2023-10-18T19:31:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-glade-5107"
primary_region = "sin"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
