# fly.toml app configuration file generated for pokedex-fullstackopen-danggro on 2023-10-18T20:03:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-fullstackopen-danggro"
primary_region = "sin"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"
    
[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[http_service]
  http_checks = []
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

