app = "Pokedex"
primary_region = "sin"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
