name: Testing stuff

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

# on:
#   push:
#     branches:
#       - feature-2

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Failing step
        id: demo
        run: exit 1
      - name: commit
        if: ${{ failure()}}
        env:
          GITHUB: ${{github.event.pull_request._links.html.href}}
        run: echo '${{ env.GITHUB }}/${{github.event.after}}'
      - name: github
        if: ${{ failure()}}
        run: |
          echo '${{ github.event.head_commit.url}} by ${{ github.event.head_commit.committer.username}} broke the build :('

  job_2:
    needs: [a_test_job]
    runs-on: ubuntu-20.04
    steps:
      - name: check
        run: echo "sda"
      - name: check 2
        if: ${{success()}}
        run: echo "success"
