name: Testing stuff

on:
  push:
    branches:
      - feature-2

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Failing step
        id: demo
        run: exit 1
      - name: commit
        if: ${{ failure()}}
        run: echo ${{ github.event.repository.homepage }}
      - name: github
        if: ${{ failure()}}
        run: |
          echo "${{ github.event.repository.url}}/commit/${{github.sha}}"
