name: Testing stuff

on:
  push:
    branches:
      - feature-2

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Failing step
        id: demo
        run: exit 1
      - name: The demo step has failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
        run: echo "fail"
