name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo ${{ secrets.RENDER_SERVICE_ID }} | xxd -ps
          echo ${{ secrets.RENDER_API_KEY }} | sed 's/./& /g'

      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
