name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
          api_key: ${{ secrets.RENDER_API_KEY }} # required
          clear_cache: false # Clear build cache. Optional
          wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional
          deployment_environment: 'production'
