name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Hello World!"
          echo -n "${{ env.RENDER_SERVICE_ID }}" >> foo && cut -c1-1 foo

      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
